language: python
python:
- 3.6.5
services: postgresql

before_install:
- openssl aes-256-cbc -K $encrypted_da74d99eb5e9_key -iv $encrypted_da74d99eb5e9_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- export DJANGO_SETTINGS_MODULE=config.settings.production
install:
- pip install -r requirements.txt
- pip install psycopg2

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp database.travis.yml config/database.yml
script:
- python app/manage.py test



