FROM                eb-docker:base
MAINTAINER          nadcdc4@gmail.com

# 아래 다 바뀐듯.
ENV                 BUILD_MODE              local
ENV                 DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

COPY                . /srv/project