# Generated by Django 2.1 on 2018-10-30 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(blank=True)),
                ('checkout_date', models.DateField(blank=True)),
                ('total_price', models.IntegerField(blank=True, default=0)),
                ('reservation_num', models.CharField(blank=True, max_length=100)),
                ('subscriber', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('method_of_payment', models.CharField(blank=True, max_length=100)),
                ('deposit_bank', models.CharField(blank=True, max_length=100)),
                ('depositor_name', models.CharField(blank=True, max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=100)),
                ('expiration_month', models.CharField(blank=True, max_length=100)),
                ('expiration_year', models.CharField(blank=True, max_length=100)),
                ('card_password', models.CharField(blank=True, max_length=100)),
                ('card_type', models.CharField(blank=True, max_length=100)),
                ('birth_date_of_owner', models.CharField(blank=True, max_length=100)),
                ('installment_plan', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='location.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
